'use client';
const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export default function CamReport({ result }) {
    if (!result) return null;
    const rr = result.risk_results || {};
    const sc = { Low: 'var(--green)', Medium: 'var(--amber)', High: 'var(--red)' };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.4rem' }}>
            <div className="grid-2" style={{ alignItems: 'start' }}>
                {/* Contents list */}
                <div className="card">
                    <div className="card-title">📄 Report Sections</div>
                    {[['1', 'Executive Summary', 'Company overview, case ID, key metrics'],
                    ['2', 'Five Cs Analysis', 'Character · Capacity · Capital · Collateral · Conditions'],
                    ['3', 'Forensic Red Flags', 'All identified flags with citations'],
                    ['4', 'Committee Decision', 'Individual votes, rationales, weighted score'],
                    ['5', 'Counterfactual Scenarios', 'What-if analysis for each risk factor'],
                    ['6', 'Final Recommendation', 'Approval/rejection with full rationale'],
                    ].map(([n, title, desc]) => (
                        <div key={n} style={{ display: 'flex', gap: '1rem', padding: '.6rem 0', borderBottom: '1px solid var(--border)', alignItems: 'flex-start' }}>
                            <div style={{ width: 24, height: 24, borderRadius: 'var(--radius-sm)', background: 'var(--blue-dark)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '.72rem', fontWeight: 700, flexShrink: 0 }}>{n}</div>
                            <div>
                                <div style={{ fontSize: '.85rem', fontWeight: 600, color: 'var(--text-primary)' }}>{title}</div>
                                <div style={{ fontSize: '.74rem', color: 'var(--text-muted)', marginTop: 2 }}>{desc}</div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Metadata + download */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                    <div className="card">
                        <div className="card-title">📋 Report Metadata</div>
                        <table className="meta-table">
                            <tbody>
                                {[['Company', result.company_name || 'N/A'],
                                ['Case ID', result.case_id || 'N/A'],
                                ['Risk Score', `${rr.total_score || 0}/100`],
                                ['Category', rr.category || 'N/A'],
                                ['Decision', rr.decision || 'N/A'],
                                ['Format', 'Microsoft Word (.docx)'],
                                ['Generated by', 'Credpanion CAM Engine v1.0'],
                                ].map(([k, v]) => (
                                    <tr key={k}>
                                        <td>{k}</td>
                                        <td style={{ fontWeight: 600, color: k === 'Decision' ? (v === 'APPROVE' ? 'var(--green)' : 'var(--red)') : k === 'Category' ? (sc[v] || 'var(--text-primary)') : 'var(--text-primary)' }}>{v}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>

                    <a className="download-btn" href={`${API}/report`} target="_blank" rel="noreferrer">
                        ⬇ Download CAM Report (.docx)
                    </a>

                    <div className="card" style={{ padding: '.9rem 1.2rem' }}>
                        <div className="card-title">💡 API Access</div>
                        <code style={{ display: 'block', fontSize: '.78rem', color: 'var(--blue)', background: 'var(--bg-base)', padding: '.6rem .8rem', borderRadius: 'var(--radius-sm)', fontFamily: 'var(--font-mono)' }}>
                            GET {API}/report
                        </code>
                    </div>
                </div>
            </div>

            {/* Five Cs preview */}
            <div className="card">
                <div className="card-title">🔑 Five Cs Credit Analysis Preview</div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: '.8rem' }}>
                    {[['Character', '⚖️', (result.legal_flags?.length || 0) > 0 ? 'Flags detected' : 'Clear'],
                    ['Capacity', '💰', `₹${((result.gst_sales || 0) / 1e6).toFixed(1)}M revenue`],
                    ['Capital', '🏭', `${Math.round((result.reality_score || 0) * 100)}% utilisation`],
                    ['Collateral', '🏠', 'Pending inspection'],
                    ['Conditions', '🌐', 'Sector norms apply'],
                    ].map(([c, icon, val]) => (
                        <div key={c} style={{ background: 'var(--bg-base)', borderRadius: 'var(--radius-md)', padding: '1rem', textAlign: 'center', border: '1px solid var(--border)' }}>
                            <div style={{ fontSize: '1.6rem', marginBottom: '.3rem' }}>{icon}</div>
                            <div style={{ fontWeight: 700, fontSize: '.82rem', color: 'var(--blue)' }}>{c}</div>
                            <div style={{ fontSize: '.73rem', color: 'var(--text-secondary)', marginTop: '.2rem' }}>{val}</div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
